In [1]:
import numpy as np

In [3]:
x = np.random.random(100000000)

In [4]:
%%time
# Pythonic
sum(x) / len(x)

CPU times: user 10.2 s, sys: 135 ms, total: 10.3 s
Wall time: 10.6 s


0.4999818462934982

In [5]:
%%time
np.mean(x)

CPU times: user 72 ms, sys: 2.96 ms, total: 75 ms
Wall time: 85.7 ms


0.49998184629357567

# Create an array with NumPy

In [8]:
x = np.array([1, 2, 3, 4, 5])
print(x)
# n-dimmensional array
print(type(x))
# return the datatype of the elements in the array
print(x.dtype)
print(x.shape)

[1 2 3 4 5]
<class 'numpy.ndarray'>
int64
(5,)


In [15]:
# 2-dimmensional Array
# Rank 2 array
Y = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
print(Y)
print()
print(type(Y))
print()
print(Y.dtype)
print()
print(Y.shape)
print()
# The number of elements in Y
print(Y.size)


[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

<class 'numpy.ndarray'>

int64

(4, 3)

12


In [16]:
x = np.array(['Hello', 'World'])
print(x)

['Hello' 'World']


In [17]:
print('shape: ', x.shape)
print('type: ', type(x))
print('dtype: ', x.dtype)

shape:  (2,)
type:  <class 'numpy.ndarray'>
dtype:  <U5


In [18]:
x = np.array([1, 2, 'World'])
print('shape: ', x.shape)
print('type: ', type(x))
print('dtype: ', x.dtype)
# The python list has mixed dataypes, but instead, numpy encoded
# them to unicode strings of 21 character

shape:  (3,)
type:  <class 'numpy.ndarray'>
dtype:  <U21


In [22]:
x = np.array([1, 2.5, 4])
print('type: ', type(x))
print('dtype: ', x.dtype)
print(x)
# NumPy upcasted the integers to floats, maintaining the same dtypes

type:  <class 'numpy.ndarray'>
dtype:  float64
[1.  2.5 4. ]


In [21]:
# Dictate the dtype for an array:
x = np.array([1, 2.5, 4], dtype=np.int64)
print('type: ', type(x))
print('dtype: ', x.dtype)
print(x)
# NumPy upcasted the integers to floats, maintaining the same dtypes

type:  <class 'numpy.ndarray'>
dtype:  int64
[1 2 4]


In [23]:
# Save an array as a file for later use:
x = np.array([1, 2, 3, 4, 5])
np.save('my_array', x)

In [24]:
y = np.load('my_array.npy')
print(y)

[1 2 3 4 5]


 # Using Built-In functions to create ndarrays

In [25]:
my_list = [1, 2, 3, 4, 5]
np.array(my_list)

array([1, 2, 3, 4, 5])

In [29]:
# Create a 3x4 array of zeroes in float 64
X = np.zeros((3, 4))
print(X)
print()
print('dtype', X.dtype)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]

dtype float64


In [30]:
# Create a 3x4 array of zeroes in int
X = np.zeros((3, 4), dtype=int)
print(X)
print()
print('dtype', X.dtype)

[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]

dtype int64


In [32]:
# Create a 4x5 array of ones in float 64
X = np.ones((4, 5))
print(X)
print()
print('dtype', X.dtype)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

dtype float64


In [35]:
# Create 4x3 array filled with a constant value of 5
X = np.full((4, 3), 5)
print(X)
print()
print('dtype', X.dtype)

[[5 5 5]
 [5 5 5]
 [5 5 5]
 [5 5 5]]

dtype int64


In [38]:
# Create the identity matrix
X = np.eye(5, dtype=int)
print(X)
print()
print('dtype', X.dtype)

[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]

dtype int64


In [39]:
# Create a diagonal with other than ones
X = np.diag([10, 20, 30, 50])
print(X)
print()
print('dtype', X.dtype)

[[10  0  0  0]
 [ 0 20  0  0]
 [ 0  0 30  0]
 [ 0  0  0 50]]

dtype int64


In [41]:
# Create a 1-d array of evenly spaced values over an interval
X = np.arange(10)
# With one argument, generates an array of integers from 0 to the
# argument-1
print(X)
print()
print('dtype', X.dtype)

[0 1 2 3 4 5 6 7 8 9]

dtype int64


In [42]:
# Create a 1-d array of evenly spaced values over an interval
X = np.arange(4, 10)
# With two arguments, generates an array of integers from the
# first argument to the second argument, exclusive of the stop
print(X)
print()
print('dtype', X.dtype)

[4 5 6 7 8 9]

dtype int64


In [43]:
# Create a 1-d array of evenly spaced values over an interval
X = np.arange(1, 14, 3)
# With three arguments, generates an array of integers from the
# first argument to the second argument, exclusive of the second,
# evenly spaced by the third argument
print(X)
print()
print('dtype', X.dtype)

[ 1  4  7 10 13]

dtype int64


In [45]:
# Creates n-evenly spaced numbers from start to stop
X = np.linspace(0, 25, 10)
# With three arguments, generates an array of floats from the
# first argument to the second argument, inclusive of the second,
# evenly spaced by the third argument
print(X)
print()
print('dtype', X.dtype)

[ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]

dtype float64


In [46]:
# Creates n-evenly spaced numbers from start to stop
X = np.linspace(0, 25, 10, endpoint=False)
# With three arguments, generates an array of floats from the
# first argument to the second argument, exclusive of the second,
# evenly spaced by the third argument
print(X)
print()
print('dtype', X.dtype)

[ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]

dtype float64


In [47]:
# We can reshape a 1-D array into any other shape as long as
# it's consistent with number of elements in the array
x = np.arange(20)
X = np.reshape(x, (4, 5))
print(x)
print()
print(X)
print()
print('dtype', X.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]

dtype int64


In [48]:
X = np.reshape(x, (10, 2))
print(x)
print()
print(X)
print()
print('dtype', X.dtype)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]

dtype int64
